name: AAPS CI

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'fullRelease'
        type: choice
        options:
          - fullRelease
          - fullDebug

jobs:
  build:
    name: Build AAPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Build APKs
        run: |
          chmod +x gradlew
          ./gradlew :app:assemble${{ github.event.inputs.buildVariant }} \
          -Pandroid.injected.signing.store.password="${{ secrets.SIGNING_PASSWORD }}" \
          -Pandroid.injected.signing.key.alias="key0" \
          -Pandroid.injected.signing.key.password="${{ secrets.ALIAS_PASSWORD }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aaps-apk
          path: app/build/outputs/apk/full/release/*.apk
